class_name ItemData
extends Resource

## Item archetype (template). Instances are plain Dictionaries generated by
## LootGenerator — this Resource defines visual identity and generation rules.

enum ItemType { WEAPON, ARMOR, ACCESSORY, LEGS, FEET }
enum Rarity { COMMON, RARE, EPIC, LEGENDARY, MYTHIC }

const RARITY_KEYS: Array[String] = ["common", "rare", "epic", "legendary", "mythic"]

# ── Export fields ─────────────────────────────────────────────────────────────

@export_category("Identité")
@export var id: String = "item_template"
@export var item_name: String = "Objet"
@export_multiline var description: String = ""
@export var item_type: ItemType = ItemType.WEAPON
@export var icon: Texture2D = null

@export_category("Génération")
## Stats pouvant être générées sur cet objet (clés de PlayerData.STAT_KEYS).
@export var stat_pool: PackedStringArray = PackedStringArray()
## Puissance de base à niveau 1, multipliée ensuite par level et rareté.
@export var base_power: int = 10

# ── Static helpers (shared with PopupManager / MainScene) ─────────────────────

static func type_string(t: int) -> String:
	match t:
		ItemType.WEAPON:    return "weapon"
		ItemType.ARMOR:     return "armor"
		ItemType.ACCESSORY: return "accessory"
		ItemType.LEGS:      return "legs"
		ItemType.FEET:      return "feet"
	return "weapon"

static func rarity_color(rarity: String) -> Color:
	match rarity:
		"common":    return Color("#aaaaaa")
		"rare":      return Color("#00f2ff")
		"epic":      return Color("#cc44ff")
		"legendary": return Color("#ffd700")
		"mythic":    return Color("#ff4444")
	return Color.WHITE

static func rarity_label(rarity: String) -> String:
	match rarity:
		"common":    return "Commun"
		"rare":      return "Rare"
		"epic":      return "Épique"
		"legendary": return "Légendaire"
		"mythic":    return "Mythique"
	return rarity
